### ISSUE TITLE
possible error (?)

### ISSUE THREAD

**Issue by Ntiboroo1** [CodeWingX/tic_tac_toe#2]
Hi,

I just popped into your code.
In your In[40] cell:
bot1 = Agent()
bot2 = Agent()
epochs = 10000
win_trace, bot1_wins, bot2_wins = train(epochs, bot1, bot2)

In the output, in epoch: 2 after O started [1,1] it says
is game stale?  False
winner found: None
No experience for this state: explore
Choose cell (0, 2)

But in epoch 1, O started [1,1] too and X lost. Shouldn't there be an experience already for X in this epoch:2?

Interestingly, in epoch:3, after the same [1,1], X has experience.
Please clarify this to me, thank you!

**Comment by ltbringer** [comment]
I am sorry each time there was an exploration turn, the message `"No experience for this state: explore"` would be printed. I have fixed that and a few other things and converted this to a module.
